name = "football"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "football-db"
database_id = "05cfe663-b33f-4d88-927f-17f98d89785f"

